Section A: Data Structures & Control Structures
1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.


In [10]:
numbers = [10,20,30,40,50]
print("orignal list:",numbers)
numbers.append(60)
print ("after append(60):",numbers)
numbers.extend([70,80])
print ("after extend([70,80]):",numbers)
numbers.insert(3,35)
print ("after insert(3,35):", numbers)
numbers.remove(30)
print ("after remove(30):", numbers)
numbers.clear()
print ("after clear():", numbers)

orignal list: [10, 20, 30, 40, 50]
after append(60): [10, 20, 30, 40, 50, 60]
after extend([70,80]): [10, 20, 30, 40, 50, 60, 70, 80]
after insert(3,35): [10, 20, 30, 35, 40, 50, 60, 70, 80]
after remove(30): [10, 20, 35, 40, 50, 60, 70, 80]
after clear(): []


2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [11]:
students = ("kavi","ravi","navi")
print("original tuples:",students) 
students[1] = "teju" 

original tuples: ('kavi', 'ravi', 'navi')


TypeError: 'tuple' object does not support item assignment

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [1]:
numbers = {20,30,50,60,30,50}
print("set",numbers)

set {50, 20, 30, 60}


Explanation:
A set in python does not allow duplicate values . 
Sets are unordered,meaning the output may not be in the same order as you typed the elements

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [3]:
person = {"Name": "shree","Age": "18", "City": "chennai",}
person["age"] = "19"
person["email"] = "shree78@gmail.com"
print("Final dictionary", person)

Final dictionary {'Name': 'shree', 'Age': '18', 'City': 'chennai', 'age': '19', 'email': 'shree78@gmail.com'}


5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [5]:
Age = 20

if Age>=18:
    print("you are eligible to vote.")
else:
    print("you are not eligible to vote.")

you are eligible to vote.


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [7]:
m1 = int(input("enter your marks: "))
m2 = int(input("enter your marks: "))
c1 = int(input("enter your marks: "))
c2 = int(input("enter your marks: "))

total = sum([m1,m2,c1,c2])

avg = total/4
print(f"your avg marks of all subjects is {avg}")
if avg>90:
    print(f"Congratulations your grade is A")
elif avg>89 and avg<=75:
    print(f"Congratulations your grade is B")
elif avg>74 and avg<=50:
    print(f"can do better you got C")
elif avg>50:
    print(f"can do more better you got fail")

your avg marks of all subjects is 66.75
can do more better you got fail


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [2]:
numbers = [-5,-4,-3,-2,-1,0,1,2,3,4,5,6]

for i in numbers:
    if i>0:
        print("positive")
    else:
        print("negative")

negative
negative
negative
negative
negative
negative
positive
positive
positive
positive
positive
positive


Section B: Numpy
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [2]:
import array
import numpy as np
scalar = np.array(5)
print("Scalar:\n", scalar)
array_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:\n", array_1d)
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])
print("\n2D Array:\n",array_2d)

Scalar:
 5

1D Array:
 [1 2 3 4 5]

2D Array:
 [[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [7]:
import numpy as np
random_array = np.random.randint(0,100,size=(4,4))
print(random_array)

[[97 64  5 32]
 [78 29 19 74]
 [66 26 18  7]
 [41 39 41 92]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [35]:
import numpy as np
import pandas as pd
numpy_array = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
column_names = ['A','B','c']
df = pd.DataFrame(numpy_array,columns=column_names)
print(df)
                        

   A  B  c
0  1  2  3
1  4  5  6
2  7  8  9


Section C: Exploring Pandas
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [36]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack'],
    'Age': [25, 32, 18, 47, 35, 29, 41, 23, 30, 52],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [50000, 65000, np.nan, 90000, 75000, 52000, np.nan, 48000, 72000, 95000]
}
df = pd.DataFrame(data)
print("DataFrame:")
print(df)

DataFrame:
      Name  Age         City   Salary
0    Alice   25     New York  50000.0
1      Bob   32  Los Angeles  65000.0
2  Charlie   18      Chicago      NaN
3    David   47      Houston  90000.0
4      Eve   35      Phoenix  75000.0
5    Frank   29     New York  52000.0
6    Grace   41  Los Angeles      NaN
7   Hannah   23      Chicago  48000.0
8      Ivy   30      Houston  72000.0
9     Jack   52      Phoenix  95000.0


In [ ]:
df.info()


--- .info() ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes


In [40]:
print(df.describe())

            Age        Salary
count  10.00000      8.000000
mean   33.20000  68375.000000
std    10.74761  17991.565484
min    18.00000  48000.000000
25%    26.00000  51500.000000
50%    31.00000  68500.000000
75%    39.50000  78750.000000
max    52.00000  95000.000000


In [45]:
selected_columns = df[['Name', 'City']]
print(selected_columns)

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4      Eve      Phoenix
5    Frank     New York
6    Grace  Los Angeles
7   Hannah      Chicago
8      Ivy      Houston
9     Jack      Phoenix


In [47]:
df = df.drop(columns=['City'])
print(df)

      Name  Age   Salary
0    Alice   25  50000.0
1      Bob   32  65000.0
2  Charlie   18      NaN
3    David   47  90000.0
4      Eve   35  75000.0
5    Frank   29  52000.0
6    Grace   41      NaN
7   Hannah   23  48000.0
8      Ivy   30  72000.0
9     Jack   52  95000.0


In [53]:
salary_mean = df['Salary']
print(salary_mean)

0    50000.0
1    65000.0
2    68375.0
3    90000.0
4    75000.0
5    52000.0
6    68375.0
7    48000.0
8    72000.0
9    95000.0
Name: Salary, dtype: float64


In [51]:
df.drop_duplicates(inplace=True)
print("\nDataFrame after dropping duplicates:")
print(df)


DataFrame after dropping duplicates:
      Name  Age   Salary
0    Alice   25  50000.0
1      Bob   32  65000.0
2  Charlie   18  68375.0
3    David   47  90000.0
4      Eve   35  75000.0
5    Frank   29  52000.0
6    Grace   41  68375.0
7   Hannah   23  48000.0
8      Ivy   30  72000.0
9     Jack   52  95000.0
